resolver: lts-11.7
# resolver: nightly-2018-05-23

packages:
- '.'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

ghc-options: {}
  # "*" : -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-imports # -fprint-potential-instances

extra-deps: []
# - Frames-0.4.0
# - pipes-text-0.0.2.5
# - ginger-0.7.3.0  
